
---
###安装 宝塔面板
- hosts: centos6
  tasks:
  - name: install centos wget tools
    shell: yum -y install wget
  - name: wget  install.sh
    shell: cd   /tmp  && wget -O install.sh http://download.bt.cn/install/install.sh
  - name: install 执行文件 
    shell: cd   /tmp   && echo  'y'  > yes &&  sh  -i install.sh    < yes
